fix lnd restart crash
Start9Labs/lightning-terminal-wrapper pull request #7
Opened 2022-09-01 19:57 UTC by islandbitcoin

#6

2022-09-01 19:59 UTC, islandbitcoin commented
Also fixed the web-check and added an LND server check.

2022-09-02 13:32 UTC, chrisguida commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
what's `vim` for?

2022-09-02 13:33 UTC, chrisguida commented on Makefile
> +install: all lightning-terminal.s9pk
the `lightning-terminal.s9pk` here is redundant. that is included in `all`

2022-09-02 13:37 UTC, islandbitcoin commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
so we can have access to xxd, which gives me the lnd macaroon in the entrypoint.

2022-09-02 13:37 UTC, islandbitcoin commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
> what's `vim` for?

so we can have access to xxd, which gives me the lnd macaroon in the entrypoint.

2022-09-02 13:40 UTC, islandbitcoin commented on Makefile
> +install: all lightning-terminal.s9pk
fixed.

2022-09-02 13:40 UTC, chrisguida commented on docker_entrypoint.sh
> +while true; do
this while loop could be a lot shorter. see: https://unix.stackexchange.com/a/644364

2022-09-02 13:46 UTC, chrisguida commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
why not just install `xxd`? it's [~300x smaller](https://pkgs.alpinelinux.org/package/edge/main/aarch64/xxd) than [vim](https://pkgs.alpinelinux.org/package/edge/main/aarch64/vim)

2022-09-02 13:47 UTC, chrisguida commented on docker_entrypoint.sh
> +wait $lightning_terminal_process
```suggestion
wait $lightning_terminal_process

```

2022-09-02 13:47 UTC, chrisguida requested changes
see comments

2022-09-02 13:52 UTC, islandbitcoin commented on docker_entrypoint.sh
> +while true; do
thanks! fixed.

2022-09-02 13:52 UTC, islandbitcoin commented on docker_entrypoint.sh
> +wait $lightning_terminal_process
fixed.

2022-09-02 13:53 UTC, islandbitcoin commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
whoa, didn't know that. I'll try installing it.

2022-09-02 13:59 UTC, islandbitcoin commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
nice, it worked. updated PR.

2022-09-02 14:00 UTC, islandbitcoin commented on Dockerfile
> +RUN apk add --no-cache yq vim curl
> why not just install `xxd`? it's [~384x smaller](https://pkgs.alpinelinux.org/package/edge/main/aarch64/xxd) than [vim](https://pkgs.alpinelinux.org/package/edge/main/aarch64/vim)

nice, it worked. updated PR.

2022-09-02 14:09 UTC, chrisguida commented on docker_entrypoint.sh
> +done
👍

2022-09-02 14:09 UTC, chrisguida approved these changes
ship it

2022-09-02 14:13 UTC, merged